---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-code-engine
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 413843d9-8962-48a5-8ab5-dfcf4429372c
    variations:
      - name: apps
        mark_ready: false
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
